name: effective_flutter_course
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.2.1
  intl: any
  json_annotation: ^4.9.0
  bloc: ^9.0.0
  dio: ^5.8.0+1
  equatable: ^2.0.7
  flutter_bloc: ^9.1.1
  cached_network_image: ^3.4.1
  scrollable_positioned_list: ^0.3.8
  bloc_concurrency: ^0.3.0
  drift: ^2.26.1
  drift_flutter: ^0.2.4
  path_provider: ^2.1.5
  yandex_mapkit: ^4.1.0
  location: ^8.0.0
  shared_preferences: ^2.5.3
  permission_handler: ^12.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  device_preview: ^1.2.0
  build_runner: ^2.4.13
  json_serializable: ^6.9.5
  drift_dev: ^2.26.1
  flutter_env_native: ^0.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
   - assets/images/placeholder.png
   - assets/images/tea.png
   - assets/images/authors_drink.png
   - assets/images/black_coffee.png
   - assets/images/coffee_with_milk.png
